name: Update M3U Radio Links

on:
  schedule:
    - cron: '0 0 1 * *' # Run daily
  workflow_dispatch:

jobs:
  update-links:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install Puppeteer
        run: |
          npm install puppeteer

      - name: Run update script
        run: node update_m3u.js

      - name: Commit and push
        uses: EndBug/add-and-commit@v10
        with:
          add: 'ipradioita.m3u'
          message: 'Update M3U radio links'
          push: true
