name: Sync and Modify

on:
  schedule:
    - cron: '0 * * * *' 
  workflow_dispatch:

jobs:
  sync-and-modify:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout Fork
        uses: actions/checkout@v4
        with:
           token: ${{ secrets.GITHUB_TOKEN }}
        env:
           FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

      - name: Sync with Upstream
        run: |
          gh repo sync ${{ github.repository }} --branch main --force
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update M3U URLs
        run: |
          # Convert DOS line endings to Unix  
          dos2unix ipradioita.m3u || true
           
          while IFS= read -r line; do
            if [[ $line =~ ^http ]]; then
              final_url=$(curl -L -s -o /dev/null -w %{url_effective} "$line")
              echo "url:$final_url"
            else
              echo "$line"
            fi
          done < ipradioita.m3u > temp.m3u
      
          sed -i '/^http/d; s/^url:http/http/g' temp.m3u
          mv temp.m3u ipradioita2.m3u
        shell: bash

      - name: Modify ipradioita.m3u
        run: |
          if [ -f "ipradioita.m3u" ]; then
            sed -i -E 's/(#EXTINF:[^,]*,)/\1 group-title="Radio" radio="true",/' ipradioita.m3u
          fi

      - name: Commit Changes
        run: |
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          
          # Stage the modified file
          git add ipradioita.m3u
          # Commit the change (if there was a modification)
          git commit -m "Modify ipradioita.m3u" || echo "No changes to commit"
          
          # Now fetch and rebase
          git fetch origin main
          git rebase origin/main
          
          git push --force-with-lease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
